### ISSUE TITLE
node01to04.mat missing

### ISSUE THREAD

**Issue by DubiousCactus** [jhonykaesemodel/compact_3D_reconstruction#3]
`ShapeNetMat.v1/02691156/node01to04.mat` is missing after downloading and extracting `data_demo.zip`. Could you check and reupload the files please ?

Thanks

**Comment by Nkcemeka** [comment]
@DubiousCactus Hi, 

Were you able to solve this error? I had the same issue while looking into this project. Commenting out the line removes the error but even with that, I seem to have something similar when running exp_full_Pascal3D.m. It says: 

```
Error using load
Unable to find file or directory '/home/matlab/Documents/MATLAB/datasets/ShapeNetMat.v1/02691156/node16to03.mat'.
```

@jhonykaesemodel Do you also have any idea on how to go about this?

**Comment by DubiousCactus** [comment]
Hi @Nkcemeka , sorry it's been 6 years now and I can't remember a thing from this project. Good luck!
